sonar.projectKey=event-driven
sonar.projectName=Event Driven Microservices
sonar.projectVersion=1.0

# App source folders
sonar.sources=ride_service/app,matching_service/app

# Test folders
sonar.tests=ride_service/tests,matching_service/tests

# Python config
sonar.python.version=3.11

# Exclusions (IMPORTANT)
sonar.exclusions=venv/**,__pycache__/**,**/*.xml,**/*.yaml,**/*.json

# Coverage (optional but recommended)
sonar.python.coverage.reportPaths=coverage.xml
